import Head from "next/head";


export default function Home() {
  return (
    <div>
      <Head>
        <title>M152 App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Index</h1>
      </main>
    </div>
  );
}
